### PR TITLE
Add configuration json file

### PR DESCRIPTION
**Pull request by denniskuczynski**
This adds a MopsConfig object that can be read and written to.

I'll use this to save password data, current group, etc.

### CODE REVIEW

**Comment by ohEmily** [comment]
Will this config file be used for login information, too? If yes, do you want to change mops-login to use your new system?

**Comment by denniskuczynski** [comment]
Yes, I'm doing that now

**Comment by ohEmily** [comment]
oh nice. Will it be a separate pull request? If yes, LGTM

**Comment by denniskuczynski** [comment]
Actually I just pushed everything to this branch.  MopsConfig should now be generic enough to put everything in.

**Comment by denniskuczynski** [comment]
master @ 64c42e4c609118b39929260ffcbdb2004a81fd20

**Pull request closed without merging**
